INSERT INTO czujniki VALUES (1,'AABBCCDDEE01');
INSERT INTO czujniki VALUES (2,'AABBCCDDEE02');
INSERT INTO czujniki VALUES (3,'AABBCCDDEE03');
INSERT INTO czujniki VALUES (4,'AABBCCDDEE04');
INSERT INTO czujniki VALUES (5,'AABBCCDDEE05');


